### ISSUE TITLE
firmware-packager incorrect makecab directive options

### ISSUE THREAD

**Issue by cnolan3** [hughsie/fwupd#1087]
The firmware-packager script doesn't set the makecab directive options correctly. The resulting cab file from the makecab.exe command isn't named as expected, so the script isn't able to find firmware.cab later on.
```
C:\Users\user\Documents\fwupd\contrib\firmware-packager>python3 firmware-packager --firmware-name aaa --device-guid aaaaaaa --developer-name aa --release-version 1 --exe APWE_400.exe --bin .\layout.bin --out \Users\user\Desktop
Using temp directory C:\Users\USER~1\AppData\Local\Temp\tmpabnt9wbq
Extracting firmware exe
Locating firmware bin
Creating metainfo
Cabbing firmware files
Cabinet Maker - Lossless Data Compression Tool

Parsing directives (C:\Users\USER~1\AppData\Local\Temp\tmpabnt9wbq\directive: 1 lines)
C:\Users\USER~1\AppData\Local\Temp\tmpabnt9wbq\directive(1): ERROR: Could not find file: firmware.cab
ERROR: MakeCAB aborted: 1 errors encountered
Traceback (most recent call last):
  File "firmware-packager", line 100, in main
    create_firmware_cab(args, dir)
  File "firmware-packager", line 82, in create_firmware_cab
    subprocess.check_call(command)
  File "C:\Python37\lib\subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['makecab.exe', '/f', 'C:\\Users\\USER~1\\AppData\\Local\\Temp\\tmpabnt9wbq\\directive']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "firmware-packager", line 120, in <module>
    main(args)
  File "firmware-packager", line 103, in main
    shutil.copy(os.path.join(dir, 'firmware.cab'), args.out)
  File "C:\Python37\lib\tempfile.py", line 805, in __exit__
    self.cleanup()
  File "C:\Python37\lib\tempfile.py", line 809, in cleanup
    _shutil.rmtree(self.name)
  File "C:\Python37\lib\shutil.py", line 513, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Python37\lib\shutil.py", line 401, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "C:\Python37\lib\shutil.py", line 399, in _rmtree_unsafe
    os.rmdir(path)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\USER~1\\AppData\\Local\\Temp\\tmpabnt9wbq'
```
I've been able to find and fix the problem, and would be happy to submit a pull request.

**Comment by superm1** [comment]
PR definitely welcome with a fix. I did test on Windows a while back so I'm curious where things broke.
